"""PR creation for evolution changes.

This module provides:
- create_evolution_pr: Create GitHub PR for evolution changes
"""

from __future__ import annotations

import asyncio
from pathlib import Path

from jpscripts.analysis.complexity import TechnicalDebtScore
from jpscripts.core.config import AppConfig
from jpscripts.core.console import get_logger
from jpscripts.git import client as git_core
from jpscripts.memory import save_memory

from .types import PRCreationResult, VerificationResult

logger = get_logger(__name__)


async def create_evolution_pr(
    repo: git_core.AsyncRepo,
    target: TechnicalDebtScore,
    branch_name: str,
    root: Path,
    config: AppConfig,
    verification: VerificationResult,
) -> PRCreationResult:
    """Create a PR for the evolution changes.

    Args:
        repo: Git repository handle
        target: The file that was optimized
        branch_name: Name of the evolution branch
        root: Workspace root directory
        config: Application configuration
        verification: Result from test verification

    Returns:
        PRCreationResult with PR URL on success
    """
    # Stage and commit
    await repo.run_git("add", "-A")
    commit_message = (
        f"refactor({target.path.stem}): reduce technical debt\n\n"
        f"Complexity score reduced from {target.complexity_score:.1f}\n"
        f"Autonomous optimization via jp evolve."
    )
    await repo.run_git("commit", "-m", commit_message)

    # Push branch
    await repo.run_git("push", "-u", "origin", branch_name)

    # Build PR body
    pr_body = f"""## Autonomous Optimization

**Target:** `{target.path}`
**Debt Score:** {target.debt_score:.1f}
**Complexity Score:** {target.complexity_score:.1f}
**Fix Frequency:** {target.fix_frequency}
**Churn:** {target.churn}

### Reasons for Selection
{chr(10).join("- " + r for r in target.reasons) if target.reasons else "- High complexity"}

### Verification
- `{verification.test_command}` -> exit {verification.exit_code}

### Changes
- Reduced cyclomatic complexity
- Improved code clarity
- Enhanced type annotations

### Test Plan
- [ ] `pytest tests/`
- [ ] `mypy --strict src/`

---
Generated by `jp evolve`
"""

    try:
        proc = await asyncio.create_subprocess_exec(
            "gh",
            "pr",
            "create",
            "--title",
            f"refactor({target.path.stem}): reduce technical debt",
            "--body",
            pr_body,
            cwd=root,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
        if proc.returncode == 0:
            pr_url = stdout.decode().strip()
            # Persist evolution success to memory
            try:
                await asyncio.to_thread(
                    save_memory,
                    f"Evolution Success: Refactored `{target.path}`. "
                    f"Complexity delta: {target.complexity_score:.1f} -> reduced. "
                    f"PR: {pr_url}",
                    ["evolution", "refactor", "success", target.path.name],
                    config=config,
                )
                logger.debug("Evolution success persisted to memory")
            except Exception as exc:
                logger.debug("Failed to persist evolution to memory: %s", exc)
            return PRCreationResult(pr_url=pr_url, success=True, error_message=None)
        else:
            error = stderr.decode().strip()
            return PRCreationResult(pr_url=None, success=False, error_message=error)
    except FileNotFoundError:
        return PRCreationResult(
            pr_url=None,
            success=False,
            error_message="gh CLI not found. Please create the PR manually.",
        )


__all__ = ["create_evolution_pr"]
